Initial commit - main/users/books/transactions c files added
saadali18/library-management-system pull request #1
Opened 2023-05-25 09:45 UTC by anniedroid

2023-05-25 18:56 UTC, saadali18 requested changes

2023-05-25 18:56 UTC, saadali18 commented on books.c
> +	enum BookTag tags[3];
Dont limit to size of 3
Please confirm the syntax

2023-05-25 18:56 UTC, saadali18 commented on books.c
> +enum BookTag { Biography, Fantasy, Fiction, Mystery, Romance, Sci_fi, Thriller, Young_adult };
Maintain consistency while initializing enums

2023-05-25 18:56 UTC, saadali18 commented on transactions.c
> +	char* check_out_date;
How we are going to accommodate splitting datetime field 
e.g struct Date
    int month
    int day
    int year

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +enum UserStatus { inactive, active, delinquent };
same as above
kindly lowercase your all enums

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +	char* login_name;
Add a comment after login_name to call it a unique field

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +	new_user->next = NULL; // Add new user to end of list
create separate function for it `CreateUser`

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +void insertNewUser(int user_id, char* full_name, char* login_name, char* password, char* email, enum Credential title, enum UserStatus status, User** head)
`insertUser`

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +void printUserList(User* head)
`printUsers`

please accommodate filters in your print function

2023-05-25 18:56 UTC, saadali18 commented on users.c
> +		case inactive:
Do some research can we find out field exact names through enums instead of 0, 1, 2, 3

2023-06-01 18:42 UTC, saadali18 requested changes

2023-06-01 18:42 UTC, saadali18 commented on books.c
> +enum book_tag { Biography, Fantasy, Fiction, Mystery, Romance, Sci_fi, Thriller, Young_adult };
Please be consistent while defining enums

2023-06-01 18:42 UTC, saadali18 commented on books.c
> +Book* createBook(long ISBN_num, char* title, int author_id, enum book_status status, enum book_tag* tags, int tag_count, int total_count, int in_stock_count, int likes)
I think we don't need likes and in_stock_count

2023-06-01 18:42 UTC, saadali18 commented on books.c
> +{
I think we should change the parameter of this function

2023-06-01 18:42 UTC, saadali18 commented on books.c
> +			default:
I think we can create separate function for book status names

2023-06-01 18:42 UTC, saadali18 commented on books.c
> +				default:
Same here

2023-06-01 18:42 UTC, saadali18 commented on users.c
> +User* librarian_list_head = NULL;
I think we can combine them

2023-06-01 18:42 UTC, saadali18 commented on users.c
> +}
I think we can move this logic in utilities file

2023-06-01 18:42 UTC, saadali18 commented on users.c
> +void printUsers(User* head)
I think we can create searchUsers function, instead of printUsers

2023-06-06 10:00 UTC, anniedroid commented on users.c
> +}
in progress

2023-06-07 06:31 UTC, saadali18 requested changes

2023-06-07 06:31 UTC, saadali18 commented on helpers.c
> +void insertNode(void* node, void** head) // Attempt to use this as template
Kindly try default parameters concept here

2023-06-07 06:31 UTC, saadali18 commented on main.c
> +{
Start building GUI as well

2023-06-09 18:46 UTC, saadali18 requested changes

2023-06-09 18:46 UTC, saadali18 commented on books.c
> +		Book* current = *head;
if !(*head)
{ 
  *head= book;
   return;
}

2023-06-09 18:46 UTC, saadali18 commented on books.c
> +}
10 books (active ,  likes).


book* filterbyLikes(int user_likes, Book **head).  (10, head)
{
  Book *filteres_books = null
  current = head;
  while current:
          if current.likes ==  user_likes
               insert_book(current, filtered_books)
   return filtered_books
} 

book* filterbyStatus(int status, Book **head).  (10, head)
{
  Book *filteres_books = null
  current = head;
  while current:
          if current.status ==  status
               insert_book(current, filtered_books)
   return filtered_books
} 

parameter{
  likes: 10
   status: 10
}

Book* filterBooks(Book* parameter, Book** head)
{
    book *filtered_books = head;
     if paratemer->likes:  filtered_books = filterbyLikes(parameter->likes, filtered_books).  O(n)
     if parameter->status:  filtered_books = filterbyStatus(parameter->status, filtered_books) O(n)
     return filtered_books;
}

2023-06-11 02:42 UTC, anniedroid commented on books.c
> +}
I found some issues with the filterBooks function code above we discussed in class:
I think: 
1) The Book* variables filter_book_on_likes, filter_book_on_status, filterbook_onID, etc - only defined within their respective if condition block and cannot be used to pass to the next if condition
2) Logical issues: the following "if" conditions are still dependent on the previous ones. For example: if parameters->status is not NULL (user passed in something to filter) but filter_book_on_like is NULL (we did'nt get anything back from last if statement), that "if filtered_books_on_likes && parameter->status" block will not run.

2023-06-16 08:21 UTC, saadali18 requested changes

2023-06-16 08:21 UTC, saadali18 commented on books.c
> +Book* filterbyBookStatus(enum book_status input_status, Book** head) // will handle convert from user input string to enum in main
Avoid unnecessary comments

2023-06-16 08:21 UTC, saadali18 commented on books.h
> +} BookCopy;
Why do we need a BookCopy struct?

2023-06-16 08:21 UTC, saadali18 commented on helpers.c
> +int countDigits(long num)
int length(long num)

2023-06-16 08:21 UTC, saadali18 commented on helpers.c
> +char* converttoString(long num)
char *toString(long num)

2023-06-16 08:21 UTC, saadali18 commented on books.c
> +Book* filterbyBookTitle(char* input_title, Book** head)
kindly be consistent with function naming
Above you are using filterbyISBN, here you are using Book keyword as well

2023-06-16 08:24 UTC, saadali18 commented
Key Points: 

Always search for buildin functions before creating custom functions
Be consistent with naming 
Avoid commented code

2023-06-25 02:45 UTC, closed without merging