Module 3
saadali18/library-management-system pull request #5
Opened 2023-07-21 07:15 UTC by anniedroid

1) Main.c
	a) Load all data - working
	b)Interface added for BOOKS pillar
		* View book - working
		* Search book - working
		* filter book - not working, codes got skipped, not prompting for input 
		* delete book: working but the returned ints that count numbers of deleted books/ copies are not accurate, returning large/negative int
	c) USERS/TRANS pillars pending
2) Auth.c/h
	change login function to return struct User* instead of bool
3) Books.c/h
	a) Added missing filter functions for counts/likes/etc(we didn't do them before because they're the same logic)
	b) Adding 2 delete functions for books/book copies
4) Users.h
	a) Adding fillterByFullName function to header file to use in main (to get users ID from user name for filterBook function)
              *

2023-07-21 15:56 UTC, saadali18 requested changes

2023-07-21 15:56 UTC, saadali18 commented on books.c
> +            return 1; // Book found and deleted, return because there should only 1 book match
As discussed in a live class, we are not going to delete record permanently from our system, we will prefer soft delete (status: inactive/deleted)

2023-07-21 15:56 UTC, saadali18 commented on main.c
> +    } while (!current_user);
This is an infinite loop, add some exit point to it.

2023-07-25 00:29 UTC, anniedroid commented
Librarian interface: book cases code running, bug fixed.

2023-07-27 16:32 UTC, saadali18 requested changes

2023-07-27 16:32 UTC, saadali18 commented on main.c
> +    int attempt = 0;
Although it will work in our use case, but practically we need to implement it other way

2023-07-27 16:32 UTC, saadali18 commented on main.c
> +    if (current_user->title == librarian) {
current_user -> title ? or current_user -> credential
kindly confirm

2023-07-27 16:32 UTC, saadali18 commented on main.c
> +                }
I think we need to remove/inactive the (current) transactions of deleted book as well

2023-07-27 16:32 UTC, saadali18 commented on main.c
> +                }
If user is author, his books should be inactive as well 
if user is customer, all his transactions should be inactive and book copies count should update

2023-07-27 16:32 UTC, saadali18 commented on main.c
> +
why this code is commented?

2023-07-27 18:11 UTC, merged